[Interface]
PrivateKey = CBebUhdUWShLsARIaibMLiYChhXgcAlceIXs8rulinI=
Address = 10.66.66.2/32,fd42:42:42::2/128
DNS = 1.1.1.1,1.0.0.1

# Uncomment the next line to set a custom MTU
# This might impact performance, so use it only if you know what you are doing
# See https://github.com/nitred/nr-wg-mtu-finder to find your optimal MTU
# MTU = 1420

[Peer]
PublicKey = pKshhjNM1/DZyTw25KZTq9+mKuYybT4/ONAcfWVeqBY=
PresharedKey = DVMK1HdQMUOSBokSCldgyTJgWyBXKa7Rey5jOSX2Bv0=
Endpoint = 13.214.214.35:51820
AllowedIPs = 0.0.0.0/0,::/0
